name: interestcalculator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.3+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  rename: ^3.0.2
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.8
  easy_url_launcher: ^0.0.7
  provider: ^6.1.2
  path: ^1.9.0
  hive: ^2.2.3
  widgets_to_image: ^1.0.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/applogo.png
  android: true
  android_12:
    color: "#ffffff"
    image: assets/icon/applogo.png
    image_dark: assets/icon/applogoinverted.png
    color_dark: "#000000"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icon/
